'use server';

import { adminClient } from '@/lib/supabase/admin';
import { revalidatePath } from 'next/cache';

/**
 * Lookup member by phone number - used for dealer onboarding verification
 * Returns member info if found, null otherwise
 */
export async function lookupMemberByPhone(phone: string): Promise<{
    found: boolean;
    member?: { id: string; full_name: string; primary_phone: string };
    error?: string;
}> {
    try {
        // Normalize Phone (support 10-digit, 12-digit with 91, or +91 format)
        const rawPhone = phone.replace(/\D/g, '');
        let formattedPhone = rawPhone;
        if (rawPhone.length === 10) {
            formattedPhone = `91${rawPhone}`;
        }

        const { data: member, error } = await adminClient
            .from('id_members')
            .select('id, full_name, primary_phone, email')
            .or(`primary_phone.eq.${rawPhone},primary_phone.eq.${formattedPhone},primary_phone.eq.+${formattedPhone}`)
            .order('created_at', { ascending: true })
            .limit(1)
            .maybeSingle();

        if (error) {
            console.error('[LookupMember] Error:', error);
            return { found: false, error: error.message };
        }

        if (!member) {
            return { found: false };
        }

        return {
            found: true,
            member: {
                id: member.id,
                full_name: member.full_name || 'Unknown',
                primary_phone: member.primary_phone || '',
                email: member.email || undefined
            }
        };
    } catch (err: any) {
        console.error('[LookupMember] Fatal:', err);
        return { found: false, error: err.message };
    }
}

/**
 * Check if a slug is available for a new dealer
 */
export async function checkSlugAvailability(slug: string): Promise<{
    available: boolean;
    suggestion?: string;
}> {
    if (!slug || slug.length < 2) {
        return { available: false };
    }

    const normalizedSlug = slug.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/(^-|-$)/g, '');

    const { data: existing } = await adminClient
        .from('id_tenants')
        .select('slug')
        .eq('slug', normalizedSlug)
        .maybeSingle();

    if (existing) {
        // Suggest alternative with number suffix
        const { count } = await adminClient
            .from('id_tenants')
            .select('*', { count: 'exact', head: true })
            .like('slug', `${normalizedSlug}%`);

        return {
            available: false,
            suggestion: `${normalizedSlug}-${(count || 0) + 1}`
        };
    }

    return { available: true };
}

export async function onboardDealer(formData: {
    dealerName: string;
    slug: string;  // Now accepts custom slug from form
    studioId?: string;
    pincode: string;
    memberId: string; // Requires verified member ID
}) {
    console.log('[OnboardDealer] Starting onboarding for:', formData.dealerName);

    try {
        // 1. Use the pre-validated slug from form (already checked for availability)
        const slug = formData.slug.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/(^-|-$)/g, '');

        if (!slug || slug.length < 2) {
            throw new Error('Invalid slug provided');
        }

        console.log('[OnboardDealer] Using slug:', slug);

        // 2. Create Tenant (display_id is auto-generated by DB trigger)
        const { data: tenant, error: tenantError } = await adminClient
            .from('id_tenants')
            .insert({
                name: formData.dealerName,
                slug,
                pincode: formData.pincode,
                type: 'DEALER',
                status: 'ACTIVE',
                studio_id: formData.studioId?.trim() || null,
                config: {},
                location: `Pincode: ${formData.pincode}`
            })
            .select()
            .single();

        if (tenantError) {
            console.error('[OnboardDealer] Tenant Error:', tenantError);
            throw tenantError;
        }

        console.log('[OnboardDealer] Tenant created:', tenant.id);

        // 3. Use the pre-verified member ID (already validated by lookupMemberByPhone)
        const memberId = formData.memberId;
        console.log('[OnboardDealer] Using verified member ID:', memberId);

        // 5. Link Member to Tenant in id_team
        const { error: teamError } = await adminClient
            .from('id_team')
            .insert({
                tenant_id: tenant.id,
                user_id: memberId,
                role: 'OWNER',
                status: 'ACTIVE'
            });

        if (teamError) {
            console.error('[OnboardDealer] Team Error:', teamError);
            if (!teamError.message.includes('unique constraint')) {
                throw teamError;
            }
        }

        console.log('[OnboardDealer] Membership created. Revalidating...');

        revalidatePath('/app/[slug]/dashboard/dealers', 'layout');
        revalidatePath('/dashboard/dealers', 'page');

        return { success: true, tenant };
    } catch (error: any) {
        console.error('[OnboardDealer] Fatal Error:', error);
        return { success: false, error: error.message || 'Check server logs' };
    }
}
