'use server';

import { adminClient } from '@/lib/supabase/admin';
import { revalidatePath } from 'next/cache';
import { getErrorMessage } from '@/lib/utils/errorMessage';
import { getPhoneLookupVariants } from '@/lib/utils/phoneUtils';

/**
 * Lookup member by phone number - used for dealer onboarding verification
 * Returns member info if found, null otherwise
 */
export async function lookupMemberByPhone(phone: string): Promise<{
    found: boolean;
    member?: { id: string; full_name: string; primary_phone: string };
    error?: string;
}> {
    try {
        const phoneVariants = getPhoneLookupVariants(phone);
        if (phoneVariants.length === 0) {
            return { found: false, error: 'Invalid phone number' };
        }
        const phoneFilter = phoneVariants.flatMap(p => [`primary_phone.eq.${p}`, `phone.eq.${p}`]).join(',');

        const { data: member, error } = await adminClient
            .from('id_members')
            .select('id, full_name, primary_phone')
            .or(phoneFilter)
            .order('created_at', { ascending: true })
            .limit(1)
            .maybeSingle();

        if (error) {
            console.error('[LookupMember] Error:', error);
            return { found: false, error: getErrorMessage(error) };
        }

        if (!member) {
            return { found: false };
        }

        return {
            found: true,
            member: {
                id: member.id,
                full_name: member.full_name || 'Unknown',
                primary_phone: member.primary_phone || '',
            },
        };
    } catch (err: unknown) {
        console.error('[LookupMember] Fatal:', err);
        return { found: false, error: getErrorMessage(err) };
    }
}

/**
 * Check if a slug is available for a new dealer
 */
export async function checkSlugAvailability(slug: string): Promise<{
    available: boolean;
    suggestion?: string;
}> {
    if (!slug || slug.length < 2) {
        return { available: false };
    }

    const normalizedSlug = slug
        .toLowerCase()
        .replace(/[^a-z0-9-]/g, '-')
        .replace(/(^-|-$)/g, '');

    const { data: existing } = await adminClient
        .from('id_tenants')
        .select('slug')
        .eq('slug', normalizedSlug)
        .maybeSingle();

    if (existing) {
        // Suggest alternative with number suffix
        const { count } = await adminClient
            .from('id_tenants')
            .select('*', { count: 'exact', head: true })
            .like('slug', `${normalizedSlug}%`);

        return {
            available: false,
            suggestion: `${normalizedSlug}-${(count || 0) + 1}`,
        };
    }

    return { available: true };
}

export async function onboardDealer(formData: {
    dealerName: string;
    slug: string; // Now accepts custom slug from form
    studioId?: string;
    pincode: string;
    memberId: string; // Requires verified member ID
}) {
    // console.log('[OnboardDealer] Starting onboarding for:', formData.dealerName);

    try {
        const normalizedStudioId = String(formData.studioId || '')
            .trim()
            .toUpperCase();
        const normalizedPincode = String(formData.pincode || '')
            .replace(/\D/g, '')
            .slice(0, 6);

        if (!/^[A-Z0-9]{3}-[A-Z0-9]{3}-[A-Z0-9]{3}$/.test(normalizedStudioId)) {
            throw new Error('Dealer code required in format XXX-XXX-XXX');
        }
        if (!/^\d{6}$/.test(normalizedPincode)) {
            throw new Error('Valid 6-digit pincode is required');
        }

        const { data: pinRow } = await adminClient
            .from('loc_pincodes')
            .select('pincode, taluka, district, state, latitude, longitude')
            .eq('pincode', normalizedPincode)
            .maybeSingle();

        const lat = Number((pinRow as any)?.latitude);
        const lng = Number((pinRow as any)?.longitude);
        if (!pinRow || !Number.isFinite(lat) || !Number.isFinite(lng)) {
            throw new Error('Coordinates missing for pincode. Dealer onboarding blocked until location is mappable.');
        }

        // 1. Use the pre-validated slug from form (already checked for availability)
        const slug = formData.slug
            .toLowerCase()
            .replace(/[^a-z0-9-]/g, '-')
            .replace(/(^-|-$)/g, '');

        if (!slug || slug.length < 2) {
            throw new Error('Invalid slug provided');
        }

        // console.log('[OnboardDealer] Using slug:', slug);

        // 2. Create Tenant (display_id is auto-generated by DB trigger)
        const { data: tenant, error: tenantError } = await adminClient
            .from('id_tenants')
            .insert({
                name: formData.dealerName,
                slug,
                pincode: normalizedPincode,
                type: 'DEALER',
                status: 'ACTIVE',
                studio_id: normalizedStudioId,
                config: {},
                location: `Pincode: ${normalizedPincode}`,
            })
            .select()
            .single();

        if (tenantError) {
            console.error('[OnboardDealer] Tenant Error:', tenantError);
            throw tenantError;
        }

        // console.log('[OnboardDealer] Tenant created:', tenant.id);

        // 3. Create canonical dealer location row with resolved coordinates.
        const { error: locationError } = await adminClient.from('id_locations').insert({
            tenant_id: tenant.id,
            name: formData.dealerName,
            type: 'DEALERSHIP',
            city: (pinRow as any).taluka || null,
            district: (pinRow as any).district || null,
            taluka: (pinRow as any).taluka || null,
            state: (pinRow as any).state || null,
            pincode: normalizedPincode,
            lat,
            lng,
            is_active: true,
        });

        if (locationError) {
            // Roll back tenant so half-onboarded inactive records don't leak in admin views.
            await adminClient.from('id_tenants').delete().eq('id', tenant.id);
            throw locationError;
        }

        // 4. Use the pre-verified member ID (already validated by lookupMemberByPhone)
        const memberId = formData.memberId;
        // console.log('[OnboardDealer] Using verified member ID:', memberId);

        // 5. Link Member to Tenant in id_team
        const { error: teamError } = await adminClient.from('id_team').insert({
            tenant_id: tenant.id,
            user_id: memberId,
            role: 'OWNER',
            status: 'ACTIVE',
        });

        if (teamError) {
            console.error('[OnboardDealer] Team Error:', teamError);
            if (!teamError.message.includes('unique constraint')) {
                throw teamError;
            }
        }

        // console.log('[OnboardDealer] Membership created. Revalidating...');

        revalidatePath('/app/[slug]/dashboard/dealers', 'layout');
        revalidatePath('/dashboard/dealers', 'page');

        return { success: true, tenant };
    } catch (error: unknown) {
        console.error('[OnboardDealer] Fatal Error:', error);
        return { success: false, error: getErrorMessage(error) || 'Check server logs' };
    }
}

/**
 * Search existing tenants by name — used for duplicate detection in onboarding modal
 */
export async function searchExistingTenants(query: string): Promise<{ id: string; name: string; slug: string }[]> {
    if (!query || query.trim().length < 2) return [];

    const { data, error } = await adminClient
        .from('id_tenants')
        .select('id, name, slug')
        .ilike('name', `%${query.trim()}%`)
        .eq('type', 'DEALER')
        .order('name')
        .limit(6);

    if (error || !data) return [];

    return data.map(t => ({ id: t.id, name: t.name, slug: t.slug }));
}
