BEGIN;

CREATE TABLE IF NOT EXISTS public.cat_price_state_mh (
  id uuid PRIMARY KEY,
  sku_id uuid NOT NULL REFERENCES public.cat_skus(id),
  state_code text NOT NULL,

  hsn_code text,
  gst_rate numeric(5,2),
  ex_factory numeric(12,2) NOT NULL,
  ex_factory_gst_amount numeric(12,2) NOT NULL,
  logistics_charges numeric(12,2) NOT NULL DEFAULT 0,
  logistics_charges_gst_amount numeric(12,2) NOT NULL DEFAULT 0,
  ex_showroom numeric(12,2) NOT NULL,

  rto_default_type text CHECK (rto_default_type IN ('STATE','BH','COMPANY')),
  rto_registration_fee_state numeric(12,2),
  rto_registration_fee_bh numeric(12,2),
  rto_registration_fee_company numeric(12,2),
  rto_smartcard_charges_state numeric(12,2),
  rto_smartcard_charges_bh numeric(12,2),
  rto_smartcard_charges_company numeric(12,2),
  rto_postal_charges_state numeric(12,2),
  rto_postal_charges_bh numeric(12,2),
  rto_postal_charges_company numeric(12,2),
  rto_roadtax_rate_state numeric(8,4),
  rto_roadtax_rate_bh numeric(8,4),
  rto_roadtax_rate_company numeric(8,4),
  rto_roadtax_amount_state numeric(12,2),
  rto_roadtax_amount_bh numeric(12,2),
  rto_roadtax_amount_company numeric(12,2),
  rto_roadtax_cess_rate_state numeric(8,4),
  rto_roadtax_cess_rate_bh numeric(8,4),
  rto_roadtax_cess_rate_company numeric(8,4),
  rto_roadtax_cess_amount_state numeric(12,2),
  rto_roadtax_cess_amount_bh numeric(12,2),
  rto_roadtax_cess_amount_company numeric(12,2),
  rto_total_state numeric(12,2),
  rto_total_bh numeric(12,2),
  rto_total_company numeric(12,2),

  ins_hsn_code text,
  ins_gst_rate numeric(5,2),
  ins_own_damage_premium_amount numeric(12,2),
  ins_own_damage_tenure_years integer,
  ins_own_damage_gst_amount numeric(12,2),
  ins_own_damage_total_amount numeric(12,2),
  ins_liability_only_premium_amount numeric(12,2),
  ins_liability_only_tenure_years integer,
  ins_liability_only_gst_amount numeric(12,2),
  ins_liability_only_total_amount numeric(12,2),
  ins_sum_mandatory_insurance numeric(12,2),
  ins_sum_mandatory_insurance_gst_amount numeric(12,2),
  ins_gross_premium numeric(12,2),
  ins_base_total numeric(12,2),
  ins_gst_total numeric(12,2),
  ins_net_premium numeric(12,2),
  ins_total numeric(12,2),
  ins_pa numeric(12,2),

  addon_zero_depreciation_amount numeric(12,2),
  addon_zero_depreciation_gst_amount numeric(12,2),
  addon_zero_depreciation_total_amount numeric(12,2),
  addon_zero_depreciation_default boolean,
  addon_engine_protector_amount numeric(12,2),
  addon_engine_protector_gst_amount numeric(12,2),
  addon_engine_protector_total_amount numeric(12,2),
  addon_engine_protector_default boolean,
  addon_return_to_invoice_amount numeric(12,2),
  addon_return_to_invoice_gst_amount numeric(12,2),
  addon_return_to_invoice_total_amount numeric(12,2),
  addon_return_to_invoice_default boolean,
  addon_consumables_cover_amount numeric(12,2),
  addon_consumables_cover_gst_amount numeric(12,2),
  addon_consumables_cover_total_amount numeric(12,2),
  addon_consumables_cover_default boolean,
  addon_roadside_assistance_amount numeric(12,2),
  addon_roadside_assistance_gst_amount numeric(12,2),
  addon_roadside_assistance_total_amount numeric(12,2),
  addon_roadside_assistance_default boolean,
  addon_key_protect_amount numeric(12,2),
  addon_key_protect_gst_amount numeric(12,2),
  addon_key_protect_total_amount numeric(12,2),
  addon_key_protect_default boolean,
  addon_tyre_protect_amount numeric(12,2),
  addon_tyre_protect_gst_amount numeric(12,2),
  addon_tyre_protect_total_amount numeric(12,2),
  addon_tyre_protect_default boolean,
  addon_pillion_cover_amount numeric(12,2),
  addon_pillion_cover_gst_amount numeric(12,2),
  addon_pillion_cover_total_amount numeric(12,2),
  addon_pillion_cover_default boolean,
  addon_personal_accident_cover_amount numeric(12,2),
  addon_personal_accident_cover_gst_amount numeric(12,2),
  addon_personal_accident_cover_total_amount numeric(12,2),
  addon_personal_accident_cover_default boolean,

  on_road_price numeric(12,2),
  publish_stage text CHECK (publish_stage IN ('DRAFT','PUBLISHED','ARCHIVED')),
  published_at timestamptz,
  published_by uuid,
  is_popular boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  CONSTRAINT uq_cat_price_state_mh_sku_state UNIQUE (sku_id, state_code),
  CONSTRAINT chk_cat_price_state_mh_ex_non_negative CHECK (
    ex_factory >= 0
    AND ex_factory_gst_amount >= 0
    AND logistics_charges >= 0
    AND logistics_charges_gst_amount >= 0
    AND ex_showroom >= 0
  )
);

CREATE INDEX IF NOT EXISTS ix_cat_price_state_mh_publish_stage
  ON public.cat_price_state_mh (publish_stage);

INSERT INTO public.cat_price_state_mh (
  id, sku_id, state_code,
  hsn_code, gst_rate, ex_factory, ex_factory_gst_amount, logistics_charges, logistics_charges_gst_amount, ex_showroom,
  rto_default_type,
  rto_registration_fee_state, rto_registration_fee_bh, rto_registration_fee_company,
  rto_smartcard_charges_state, rto_smartcard_charges_bh, rto_smartcard_charges_company,
  rto_postal_charges_state, rto_postal_charges_bh, rto_postal_charges_company,
  rto_roadtax_rate_state, rto_roadtax_rate_bh, rto_roadtax_rate_company,
  rto_roadtax_amount_state, rto_roadtax_amount_bh, rto_roadtax_amount_company,
  rto_roadtax_cess_rate_state, rto_roadtax_cess_rate_bh, rto_roadtax_cess_rate_company,
  rto_roadtax_cess_amount_state, rto_roadtax_cess_amount_bh, rto_roadtax_cess_amount_company,
  rto_total_state, rto_total_bh, rto_total_company,
  ins_hsn_code, ins_gst_rate,
  ins_own_damage_premium_amount, ins_own_damage_tenure_years, ins_own_damage_gst_amount, ins_own_damage_total_amount,
  ins_liability_only_premium_amount, ins_liability_only_tenure_years, ins_liability_only_gst_amount, ins_liability_only_total_amount,
  ins_sum_mandatory_insurance, ins_sum_mandatory_insurance_gst_amount, ins_gross_premium,
  ins_base_total, ins_gst_total, ins_net_premium, ins_total, ins_pa,
  addon_zero_depreciation_amount, addon_zero_depreciation_gst_amount, addon_zero_depreciation_total_amount, addon_zero_depreciation_default,
  addon_engine_protector_amount, addon_engine_protector_gst_amount, addon_engine_protector_total_amount, addon_engine_protector_default,
  addon_return_to_invoice_amount, addon_return_to_invoice_gst_amount, addon_return_to_invoice_total_amount, addon_return_to_invoice_default,
  addon_consumables_cover_amount, addon_consumables_cover_gst_amount, addon_consumables_cover_total_amount, addon_consumables_cover_default,
  addon_roadside_assistance_amount, addon_roadside_assistance_gst_amount, addon_roadside_assistance_total_amount, addon_roadside_assistance_default,
  addon_key_protect_amount, addon_key_protect_gst_amount, addon_key_protect_total_amount, addon_key_protect_default,
  addon_tyre_protect_amount, addon_tyre_protect_gst_amount, addon_tyre_protect_total_amount, addon_tyre_protect_default,
  addon_pillion_cover_amount, addon_pillion_cover_gst_amount, addon_pillion_cover_total_amount, addon_pillion_cover_default,
  addon_personal_accident_cover_amount, addon_personal_accident_cover_gst_amount, addon_personal_accident_cover_total_amount, addon_personal_accident_cover_default,
  on_road_price, publish_stage, published_at, published_by, is_popular, created_at, updated_at
)
SELECT
  src.id,
  src.sku_id,
  src.state_code,
  src.hsn_code,
  src.gst_rate,
  COALESCE(src.ex_showroom_basic,
           CASE WHEN COALESCE(src.gst_rate, 0) > 0 THEN ROUND(COALESCE(src.ex_showroom_total, src.ex_showroom, 0) / (1 + src.gst_rate / 100.0), 2)
                ELSE COALESCE(src.ex_showroom_total, src.ex_showroom, 0) END,
           COALESCE(src.ex_showroom_total, src.ex_showroom, 0)) AS ex_factory,
  COALESCE(src.ex_showroom_gst_amount,
           COALESCE(src.ex_showroom_total, src.ex_showroom, 0)
             - COALESCE(src.ex_showroom_basic,
                        CASE WHEN COALESCE(src.gst_rate, 0) > 0 THEN ROUND(COALESCE(src.ex_showroom_total, src.ex_showroom, 0) / (1 + src.gst_rate / 100.0), 2)
                             ELSE COALESCE(src.ex_showroom_total, src.ex_showroom, 0) END,
                        COALESCE(src.ex_showroom_total, src.ex_showroom, 0)),
           0) AS ex_factory_gst_amount,
  0::numeric(12,2) AS logistics_charges,
  0::numeric(12,2) AS logistics_charges_gst_amount,
  COALESCE(src.ex_showroom_total, src.ex_showroom, 0) AS ex_showroom,

  src.rto_default_type,
  src.rto_registration_fee_state,
  src.rto_registration_fee_bh,
  src.rto_registration_fee_company,
  src.rto_smartcard_charges_state,
  src.rto_smartcard_charges_bh,
  src.rto_smartcard_charges_company,
  src.rto_postal_charges_state,
  src.rto_postal_charges_bh,
  src.rto_postal_charges_company,
  src.rto_roadtax_rate_state,
  src.rto_roadtax_rate_bh,
  src.rto_roadtax_rate_company,
  src.rto_roadtax_amount_state,
  src.rto_roadtax_amount_bh,
  src.rto_roadtax_amount_company,
  src.rto_roadtaxcess_rate_state,
  src.rto_roadtaxcess_rate_bh,
  src.rto_roadtaxcess_rate_company,
  src.rto_roadtaxcessamount_state,
  src.rto_roadtaxcessamount_bh,
  src.rto_roadtaxcessamount_company,
  src.rto_total_state,
  src.rto_total_bh,
  src.rto_total_company,

  COALESCE(src.hsn_insurance, src.hsn_code) AS ins_hsn_code,
  COALESCE(src.gst_rate_insurance, src.ins_gst_rate::numeric, src.gst_rate) AS ins_gst_rate,
  COALESCE(src.ins_od_base, 0)::numeric(12,2) AS ins_own_damage_premium_amount,
  1 AS ins_own_damage_tenure_years,
  COALESCE(src.ins_od_gst, 0)::numeric(12,2) AS ins_own_damage_gst_amount,
  COALESCE(src.ins_od_total, 0)::numeric(12,2) AS ins_own_damage_total_amount,
  COALESCE(src.ins_tp_base, 0)::numeric(12,2) AS ins_liability_only_premium_amount,
  5 AS ins_liability_only_tenure_years,
  COALESCE(src.ins_tp_gst, 0)::numeric(12,2) AS ins_liability_only_gst_amount,
  COALESCE(src.ins_tp_total, 0)::numeric(12,2) AS ins_liability_only_total_amount,
  (COALESCE(src.ins_od_base, 0) + COALESCE(src.ins_tp_base, 0))::numeric(12,2) AS ins_sum_mandatory_insurance,
  (COALESCE(src.ins_od_gst, 0) + COALESCE(src.ins_tp_gst, 0))::numeric(12,2) AS ins_sum_mandatory_insurance_gst_amount,
  ((COALESCE(src.ins_od_base, 0) + COALESCE(src.ins_tp_base, 0))
    + (COALESCE(src.ins_od_gst, 0) + COALESCE(src.ins_tp_gst, 0)))::numeric(12,2) AS ins_gross_premium,
  COALESCE(src.ins_base_total, 0)::numeric(12,2) AS ins_base_total,
  COALESCE(src.ins_gst_total, 0)::numeric(12,2) AS ins_gst_total,
  COALESCE(src.ins_net_premium, 0)::numeric(12,2) AS ins_net_premium,
  COALESCE(src.ins_total, 0)::numeric(12,2) AS ins_total,
  COALESCE(src.ins_pa, 0)::numeric(12,2) AS ins_pa,

  src.addon_zerodepreciation_amount::numeric(12,2) AS addon_zero_depreciation_amount,
  src.addon_zerodepreciation_gstamount::numeric(12,2) AS addon_zero_depreciation_gst_amount,
  src.addon_zerodepreciation_total::numeric(12,2) AS addon_zero_depreciation_total_amount,
  src.addon_zerodepreciation_default AS addon_zero_depreciation_default,
  NULL::numeric(12,2) AS addon_engine_protector_amount,
  NULL::numeric(12,2) AS addon_engine_protector_gst_amount,
  NULL::numeric(12,2) AS addon_engine_protector_total_amount,
  NULL::boolean AS addon_engine_protector_default,
  NULL::numeric(12,2) AS addon_return_to_invoice_amount,
  NULL::numeric(12,2) AS addon_return_to_invoice_gst_amount,
  NULL::numeric(12,2) AS addon_return_to_invoice_total_amount,
  NULL::boolean AS addon_return_to_invoice_default,
  NULL::numeric(12,2) AS addon_consumables_cover_amount,
  NULL::numeric(12,2) AS addon_consumables_cover_gst_amount,
  NULL::numeric(12,2) AS addon_consumables_cover_total_amount,
  NULL::boolean AS addon_consumables_cover_default,
  NULL::numeric(12,2) AS addon_roadside_assistance_amount,
  NULL::numeric(12,2) AS addon_roadside_assistance_gst_amount,
  NULL::numeric(12,2) AS addon_roadside_assistance_total_amount,
  NULL::boolean AS addon_roadside_assistance_default,
  NULL::numeric(12,2) AS addon_key_protect_amount,
  NULL::numeric(12,2) AS addon_key_protect_gst_amount,
  NULL::numeric(12,2) AS addon_key_protect_total_amount,
  NULL::boolean AS addon_key_protect_default,
  NULL::numeric(12,2) AS addon_tyre_protect_amount,
  NULL::numeric(12,2) AS addon_tyre_protect_gst_amount,
  NULL::numeric(12,2) AS addon_tyre_protect_total_amount,
  NULL::boolean AS addon_tyre_protect_default,
  NULL::numeric(12,2) AS addon_pillion_cover_amount,
  NULL::numeric(12,2) AS addon_pillion_cover_gst_amount,
  NULL::numeric(12,2) AS addon_pillion_cover_total_amount,
  NULL::boolean AS addon_pillion_cover_default,
  src.addon_pa_amount::numeric(12,2) AS addon_personal_accident_cover_amount,
  src.addon_pa_gstamount::numeric(12,2) AS addon_personal_accident_cover_gst_amount,
  src.addon_pa_total::numeric(12,2) AS addon_personal_accident_cover_total_amount,
  src.addon_pa_default AS addon_personal_accident_cover_default,

  src.on_road_price,
  src.publish_stage,
  src.published_at,
  src.published_by,
  src.is_popular,
  src.created_at,
  src.updated_at
FROM public.cat_price_mh src
ON CONFLICT (sku_id, state_code) DO UPDATE SET
  hsn_code = EXCLUDED.hsn_code,
  gst_rate = EXCLUDED.gst_rate,
  ex_factory = EXCLUDED.ex_factory,
  ex_factory_gst_amount = EXCLUDED.ex_factory_gst_amount,
  logistics_charges = EXCLUDED.logistics_charges,
  logistics_charges_gst_amount = EXCLUDED.logistics_charges_gst_amount,
  ex_showroom = EXCLUDED.ex_showroom,
  rto_default_type = EXCLUDED.rto_default_type,
  rto_registration_fee_state = EXCLUDED.rto_registration_fee_state,
  rto_registration_fee_bh = EXCLUDED.rto_registration_fee_bh,
  rto_registration_fee_company = EXCLUDED.rto_registration_fee_company,
  rto_smartcard_charges_state = EXCLUDED.rto_smartcard_charges_state,
  rto_smartcard_charges_bh = EXCLUDED.rto_smartcard_charges_bh,
  rto_smartcard_charges_company = EXCLUDED.rto_smartcard_charges_company,
  rto_postal_charges_state = EXCLUDED.rto_postal_charges_state,
  rto_postal_charges_bh = EXCLUDED.rto_postal_charges_bh,
  rto_postal_charges_company = EXCLUDED.rto_postal_charges_company,
  rto_roadtax_rate_state = EXCLUDED.rto_roadtax_rate_state,
  rto_roadtax_rate_bh = EXCLUDED.rto_roadtax_rate_bh,
  rto_roadtax_rate_company = EXCLUDED.rto_roadtax_rate_company,
  rto_roadtax_amount_state = EXCLUDED.rto_roadtax_amount_state,
  rto_roadtax_amount_bh = EXCLUDED.rto_roadtax_amount_bh,
  rto_roadtax_amount_company = EXCLUDED.rto_roadtax_amount_company,
  rto_roadtax_cess_rate_state = EXCLUDED.rto_roadtax_cess_rate_state,
  rto_roadtax_cess_rate_bh = EXCLUDED.rto_roadtax_cess_rate_bh,
  rto_roadtax_cess_rate_company = EXCLUDED.rto_roadtax_cess_rate_company,
  rto_roadtax_cess_amount_state = EXCLUDED.rto_roadtax_cess_amount_state,
  rto_roadtax_cess_amount_bh = EXCLUDED.rto_roadtax_cess_amount_bh,
  rto_roadtax_cess_amount_company = EXCLUDED.rto_roadtax_cess_amount_company,
  rto_total_state = EXCLUDED.rto_total_state,
  rto_total_bh = EXCLUDED.rto_total_bh,
  rto_total_company = EXCLUDED.rto_total_company,
  ins_hsn_code = EXCLUDED.ins_hsn_code,
  ins_gst_rate = EXCLUDED.ins_gst_rate,
  ins_own_damage_premium_amount = EXCLUDED.ins_own_damage_premium_amount,
  ins_own_damage_tenure_years = EXCLUDED.ins_own_damage_tenure_years,
  ins_own_damage_gst_amount = EXCLUDED.ins_own_damage_gst_amount,
  ins_own_damage_total_amount = EXCLUDED.ins_own_damage_total_amount,
  ins_liability_only_premium_amount = EXCLUDED.ins_liability_only_premium_amount,
  ins_liability_only_tenure_years = EXCLUDED.ins_liability_only_tenure_years,
  ins_liability_only_gst_amount = EXCLUDED.ins_liability_only_gst_amount,
  ins_liability_only_total_amount = EXCLUDED.ins_liability_only_total_amount,
  ins_sum_mandatory_insurance = EXCLUDED.ins_sum_mandatory_insurance,
  ins_sum_mandatory_insurance_gst_amount = EXCLUDED.ins_sum_mandatory_insurance_gst_amount,
  ins_gross_premium = EXCLUDED.ins_gross_premium,
  ins_base_total = EXCLUDED.ins_base_total,
  ins_gst_total = EXCLUDED.ins_gst_total,
  ins_net_premium = EXCLUDED.ins_net_premium,
  ins_total = EXCLUDED.ins_total,
  ins_pa = EXCLUDED.ins_pa,
  addon_zero_depreciation_amount = EXCLUDED.addon_zero_depreciation_amount,
  addon_zero_depreciation_gst_amount = EXCLUDED.addon_zero_depreciation_gst_amount,
  addon_zero_depreciation_total_amount = EXCLUDED.addon_zero_depreciation_total_amount,
  addon_zero_depreciation_default = EXCLUDED.addon_zero_depreciation_default,
  addon_engine_protector_amount = EXCLUDED.addon_engine_protector_amount,
  addon_engine_protector_gst_amount = EXCLUDED.addon_engine_protector_gst_amount,
  addon_engine_protector_total_amount = EXCLUDED.addon_engine_protector_total_amount,
  addon_engine_protector_default = EXCLUDED.addon_engine_protector_default,
  addon_return_to_invoice_amount = EXCLUDED.addon_return_to_invoice_amount,
  addon_return_to_invoice_gst_amount = EXCLUDED.addon_return_to_invoice_gst_amount,
  addon_return_to_invoice_total_amount = EXCLUDED.addon_return_to_invoice_total_amount,
  addon_return_to_invoice_default = EXCLUDED.addon_return_to_invoice_default,
  addon_consumables_cover_amount = EXCLUDED.addon_consumables_cover_amount,
  addon_consumables_cover_gst_amount = EXCLUDED.addon_consumables_cover_gst_amount,
  addon_consumables_cover_total_amount = EXCLUDED.addon_consumables_cover_total_amount,
  addon_consumables_cover_default = EXCLUDED.addon_consumables_cover_default,
  addon_roadside_assistance_amount = EXCLUDED.addon_roadside_assistance_amount,
  addon_roadside_assistance_gst_amount = EXCLUDED.addon_roadside_assistance_gst_amount,
  addon_roadside_assistance_total_amount = EXCLUDED.addon_roadside_assistance_total_amount,
  addon_roadside_assistance_default = EXCLUDED.addon_roadside_assistance_default,
  addon_key_protect_amount = EXCLUDED.addon_key_protect_amount,
  addon_key_protect_gst_amount = EXCLUDED.addon_key_protect_gst_amount,
  addon_key_protect_total_amount = EXCLUDED.addon_key_protect_total_amount,
  addon_key_protect_default = EXCLUDED.addon_key_protect_default,
  addon_tyre_protect_amount = EXCLUDED.addon_tyre_protect_amount,
  addon_tyre_protect_gst_amount = EXCLUDED.addon_tyre_protect_gst_amount,
  addon_tyre_protect_total_amount = EXCLUDED.addon_tyre_protect_total_amount,
  addon_tyre_protect_default = EXCLUDED.addon_tyre_protect_default,
  addon_pillion_cover_amount = EXCLUDED.addon_pillion_cover_amount,
  addon_pillion_cover_gst_amount = EXCLUDED.addon_pillion_cover_gst_amount,
  addon_pillion_cover_total_amount = EXCLUDED.addon_pillion_cover_total_amount,
  addon_pillion_cover_default = EXCLUDED.addon_pillion_cover_default,
  addon_personal_accident_cover_amount = EXCLUDED.addon_personal_accident_cover_amount,
  addon_personal_accident_cover_gst_amount = EXCLUDED.addon_personal_accident_cover_gst_amount,
  addon_personal_accident_cover_total_amount = EXCLUDED.addon_personal_accident_cover_total_amount,
  addon_personal_accident_cover_default = EXCLUDED.addon_personal_accident_cover_default,
  on_road_price = EXCLUDED.on_road_price,
  publish_stage = EXCLUDED.publish_stage,
  published_at = EXCLUDED.published_at,
  published_by = EXCLUDED.published_by,
  is_popular = EXCLUDED.is_popular,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

COMMIT;
